name: Build and Deploy Zabbix

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build builder image
        run: docker build -t zabbix-alpine-builder .
<<<<<<< HEAD
=======
        working-directory: Exercise2
>>>>>>> 713290a (Add Exercise2 CI/CD pipeline and GitHub Actions workflow)

      - name: Build Zabbix APK
        run: |
          mkdir -p ${{ github.workspace }}/packages
          docker run --rm \
            -v ${{ github.workspace }}:/src:ro  \
            -v ${{ github.workspace }}/packages:/home/builder/packages \
            zabbix-alpine-builder \
            sh -c "
              doas apk update &&
              doas chown -R builder:builder /home/builder/packages &&
              cp -r /src /tmp/build &&
              chown -R builder:builder /tmp/build &&
              cd /tmp/build &&
              abuild-keygen -a -n &&
              doas cp /home/builder/.abuild/*.pub /etc/apk/keys/ &&
              abuild checksum &&
              abuild -r
            "

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zabbix-apk
          path: packages/**/*.apk